id: I5F9454F5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:03:21+00:00'
last_modified: '2022-06-07T13:40:46.261251+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4335
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་གཞུང་ལུགས་ཕྱོགས་བསྒྲིགས། ༼དང་པོ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    555D:
      image_group_id: I1KG4357
      title: ''
      total_pages: 820
      order: 1
      base_file: 555D.txt
    '3036':
      image_group_id: I1KG4358
      title: ''
      total_pages: 718
      order: 2
      base_file: 3036.txt
    '1834':
      image_group_id: I1KG4359
      title: ''
      total_pages: 824
      order: 3
      base_file: 1834.txt
    DDFB:
      image_group_id: I1KG4360
      title: ''
      total_pages: 648
      order: 4
      base_file: DDFB.txt
    DFB8:
      image_group_id: I1KG4361
      title: ''
      total_pages: 842
      order: 5
      base_file: DFB8.txt
    0939:
      image_group_id: I1KG4362
      title: ''
      total_pages: 594
      order: 6
      base_file: 0939.txt
    124B:
      image_group_id: I1KG4363
      title: ''
      total_pages: 580
      order: 7
      base_file: 124B.txt
    '2605':
      image_group_id: I1KG4364
      title: ''
      total_pages: 1068
      order: 8
      base_file: 2605.txt
    383A:
      image_group_id: I1KG4365
      title: ''
      total_pages: 1328
      order: 9
      base_file: 383A.txt
    F810:
      image_group_id: I1KG4366
      title: ''
      total_pages: 390
      order: 10
      base_file: F810.txt
    6C86:
      image_group_id: I1KG4367
      title: ''
      total_pages: 748
      order: 11
      base_file: 6C86.txt
    6A49:
      image_group_id: I1KG4368
      title: ''
      total_pages: 322
      order: 12
      base_file: 6A49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
