id: I5F9454F5
legacy_id: P000770
ocr_import_info:
  bdrc_scan_id: W1KG4335
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T19:58:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:32:12.408102+00:00'
last_modified: 2022-09-01 00:37:06.324711
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4335
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4335
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་གཞུང་ལུགས་ཕྱོགས་བསྒྲིགས། ༼དང་པོ།༽
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6818111754744115
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1KG4359:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4359
      total_pages: 824
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG4359.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7042421173115163
    legacy_id: v003
  I1KG4362:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4362
      total_pages: 594
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG4362.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7126438061140561
    legacy_id: v006
  I1KG4360:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4360
      total_pages: 648
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG4360.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6953491120102319
    legacy_id: v004
  I1KG4364:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4364
      total_pages: 1068
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG4364.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6189212414097862
    legacy_id: v008
  I1KG4357:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4357
      total_pages: 820
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4357.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7007022852311777
    legacy_id: v001
  I1KG4366:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4366
      total_pages: 390
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG4366.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6941154349582132
    legacy_id: v010
  I1KG4361:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4361
      total_pages: 842
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG4361.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6935868585082662
    legacy_id: v005
  I1KG4367:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4367
      total_pages: 748
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG4367.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6967204768822016
    legacy_id: v011
  I1KG4365:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4365
      total_pages: 1328
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG4365.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6593059159773499
    legacy_id: v009
  I1KG4363:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4363
      total_pages: 580
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG4363.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6759134196534149
    legacy_id: v007
  I1KG4368:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4368
      total_pages: 322
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG4368.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.685240811558513
    legacy_id: v012
  I1KG4358:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4358
      total_pages: 718
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4358.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7112837133335425
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
