id: P000770
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4335
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་གཞུང་ལུགས་ཕྱོགས་བསྒྲིགས། ༼དང་པོ།༽
  author: ''
  volumes:
    b4be1246a85c404d97e320cfbe85b98b:
      image_group_id: I1KG4357
      title: ''
      volume_number: 1
      total_pages: 820
      base_file: v001.txt
    f4dc8cf7554d414e82c8999170a01f46:
      image_group_id: I1KG4358
      title: ''
      volume_number: 2
      total_pages: 718
      base_file: v002.txt
    b2d8eaf59a90411396ad9018b850c42f:
      image_group_id: I1KG4359
      title: ''
      volume_number: 3
      total_pages: 824
      base_file: v003.txt
    3bb2c2335447411ba418cce71e6991a2:
      image_group_id: I1KG4360
      title: ''
      volume_number: 4
      total_pages: 648
      base_file: v004.txt
    29f9bf6608a94577a8429c4fc7ef1523:
      image_group_id: I1KG4361
      title: ''
      volume_number: 5
      total_pages: 842
      base_file: v005.txt
    eb71df2fbe874bf1b689c8e303fd428e:
      image_group_id: I1KG4362
      title: ''
      volume_number: 6
      total_pages: 594
      base_file: v006.txt
    2b2c102b4b3941cab8413c3bffb29090:
      image_group_id: I1KG4363
      title: ''
      volume_number: 7
      total_pages: 580
      base_file: v007.txt
    a0988095628c439698528777d2cc8fe6:
      image_group_id: I1KG4364
      title: ''
      volume_number: 8
      total_pages: 1068
      base_file: v008.txt
    273884d3729945ce8d7ea2e10ae2c088:
      image_group_id: I1KG4365
      title: ''
      volume_number: 9
      total_pages: 1328
      base_file: v009.txt
    1708815781bd4021a52e98699667c804:
      image_group_id: I1KG4366
      title: ''
      volume_number: 10
      total_pages: 390
      base_file: v010.txt
    79e3c349bfce42ba861d9463086019e0:
      image_group_id: I1KG4367
      title: ''
      volume_number: 11
      total_pages: 748
      base_file: v011.txt
    1bcbe9b1a4ea45fb972b59e4cca8b1fe:
      image_group_id: I1KG4368
      title: ''
      volume_number: 12
      total_pages: 322
      base_file: v012.txt
